### ISSUE TITLE
Fatal error: semaphore.h: No such file or directory

### ISSUE THREAD

**Issue by hannanahmed1** [sudam-chavan/internet-controlled-switch#1]
Arduino: 1.8.1 (Windows 7), Board: "Adafruit HUZZAH ESP8266, 80 MHz, 115200, 4M (3M SPIFFS)"

Build options changed, rebuilding all
In file included from C:\Users\sajjad\Documents\Arduino\libraries\src\StackTrace.h:22:0,

                 from C:\Users\sajjad\Documents\Arduino\libraries\src\Heap.c:31:

C:\Users\sajjad\Documents\Arduino\libraries\src\Thread.h:47:26: fatal error: semaphore.h: No such file or directory

    #include <semaphore.h>

                          ^

compilation terminated.

exit status 1
Error compiling for board Adafruit HUZZAH ESP8266.

This report would have more information with
"Show verbose output during compilation"
option enabled in File -> Preferences.

**Comment by sudam-chavan** [comment]
The error says it all. I think your Arduino IDE is not able to see your library folder Or your library path is wrong.

**Comment by hannanahmed1** [comment]
i think you code this in linux , but im using windows

**Comment by sudam-chavan** [comment]
Please increase the verbosity of compilation process through File -> Preferences. And paste the logs
